Repository jobflearn/jobflearn, pull requests merged in 2023-06, with the labels that each got.

#4 rename: 디렉토리 구조 개선
  src/main/java/kr/binarybard/hireo/auth/controller/LoginController.java
  src/main/java/kr/binarybard/hireo/auth/service/LoginService.java
  src/main/java/kr/binarybard/hireo/config/CommonConfig.java
  src/main/java/kr/binarybard/hireo/member/controller/MainController.java
  src/main/java/kr/binarybard/hireo/member/domain/BaseTimeEntity.java
  src/main/java/kr/binarybard/hireo/member/domain/Member.java
  src/main/java/kr/binarybard/hireo/member/domain/Role.java
  src/main/java/kr/binarybard/hireo/member/dto/MemberDto.java
  src/main/java/kr/binarybard/hireo/member/dto/MemberMapper.java
  src/main/java/kr/binarybard/hireo/member/repository/MemberRepository.java
  src/main/java/kr/binarybard/hireo/member/service/MemberService.java
  src/main/java/kr/binarybard/hireo/service/MemberService.java
Labels: 👀 review

#9 Hir 4 login
  src/main/java/kr/binarybard/hireo/auth/controller/LoginController.java
  src/main/java/kr/binarybard/hireo/auth/dto/SignUpRequest.java
  src/main/java/kr/binarybard/hireo/auth/service/LoginService.java
  src/main/java/kr/binarybard/hireo/config/SecurityConfig.java
  src/main/resources/templates/login.html
  src/main/resources/templates/new.html
  src/main/resources/templates/templates/layouts/home.html
Labels: 🆕 enhancement, 👀 review

#10 HIR-3 feat: 카카오 및 구글을 통한 소셜 로그인 기능 구현
  build.gradle
  src/main/java/kr/binarybard/hireo/config/SecurityConfig.java
  src/main/java/kr/binarybard/hireo/config/oauth/CustomOAuth2UserPrincipal.java
  src/main/java/kr/binarybard/hireo/config/oauth/CustomOAuth2UserService.java
  src/main/java/kr/binarybard/hireo/config/oauth/userinfo/CustomOAuth2Provider.java
  src/main/java/kr/binarybard/hireo/config/oauth/userinfo/CustomOAuth2UserInfo.java
  src/main/java/kr/binarybard/hireo/config/oauth/userinfo/GoogleOAuth2UserInfo.java
  src/main/java/kr/binarybard/hireo/config/oauth/userinfo/KakaoOAuth2UserInfo.java
  src/main/java/kr/binarybard/hireo/exception/UnsupportedOAuth2ProviderException.java
  src/main/java/kr/binarybard/hireo/utils/ConvertUtils.java
  src/main/resources/messages.properties
  src/main/resources/static/css/icons.css
  src/main/resources/static/css/style.css
  src/main/resources/static/fonts/Brand-Icons.svg
  src/main/resources/static/fonts/Brand-Icons.ttf
  src/main/resources/static/fonts/Brand-Icons.woff
  src/main/resources/static/js/custom.js
  src/main/resources/templates/login.html
  src/main/resources/templates/new.html
  src/main/resources/templates/templates/layouts/home.html
Labels: 🆕 enhancement, 👀 review

#12 HIR-12 feat: 기본적인 CompanyService 기능 추가
  src/main/java/kr/binarybard/hireo/exception/CompanyNotFoundException.java
  src/main/java/kr/binarybard/hireo/web/company/domain/Company.java
  src/main/java/kr/binarybard/hireo/web/company/dto/CompanyMapper.java
  src/main/java/kr/binarybard/hireo/web/company/dto/CompanyRegister.java
  src/main/java/kr/binarybard/hireo/web/company/dto/CompanyResponse.java
  src/main/java/kr/binarybard/hireo/web/company/repository/CompanyRepository.java
  src/main/java/kr/binarybard/hireo/web/company/service/CompanyService.java
  src/main/java/kr/binarybard/hireo/web/location/domain/Address.java
  src/main/java/kr/binarybard/hireo/web/location/domain/Location.java
  src/main/java/kr/binarybard/hireo/web/location/dto/LocationDto.java
  src/main/java/kr/binarybard/hireo/web/location/dto/LocationMapper.java
  src/main/java/kr/binarybard/hireo/web/location/repository/LocationRepository.java
  src/main/java/kr/binarybard/hireo/web/member/domain/Member.java
  src/main/resources/static/company-form.html
  src/test/java/kr/binarybard/hireo/web/company/service/CompanyServiceTest.java
  src/test/java/kr/binarybard/hireo/web/fixture/CompanyFixture.java
  src/test/java/kr/binarybard/hireo/web/fixture/CompanyRegisterFixture.java
  src/test/java/kr/binarybard/hireo/web/fixture/CompanyReponseFixture.java
  src/test/java/kr/binarybard/hireo/web/fixture/LocationDtoFixture.java
  src/test/java/kr/binarybard/hireo/web/fixture/LocationFixture.java
Labels: 🆕 enhancement, 👀 review

#13 HIR-25 feat: 사용자의 ID와 비밀번호를 받아 JWT 토큰을 생성하는 API를 구현한다.
  .github/workflows/sonar.yml
  build.gradle
  src/main/java/kr/binarybard/hireo/api/auth/controller/AuthenticationApiController.java
  src/main/java/kr/binarybard/hireo/api/auth/domain/RefreshToken.java
  src/main/java/kr/binarybard/hireo/api/auth/dto/RefreshTokenRequest.java
  src/main/java/kr/binarybard/hireo/api/auth/dto/SignInRequest.java
  src/main/java/kr/binarybard/hireo/api/auth/repository/RefreshTokenRepository.java
  src/main/java/kr/binarybard/hireo/api/auth/service/RefreshTokenService.java
  src/main/java/kr/binarybard/hireo/config/SecurityConfig.java
  src/main/java/kr/binarybard/hireo/config/jwt/JwtTokenProvider.java
  src/main/resources/application.yml
  src/test/java/kr/binarybard/hireo/api/auth/controller/AuthenticationApiControllerTest.java
  src/test/java/kr/binarybard/hireo/api/auth/service/RefreshTokenServiceTest.java
  src/test/java/kr/binarybard/hireo/utils/ConvertUtilsTest.java
  src/test/java/kr/binarybard/hireo/web/auth/controller/LoginControllerTest.java
  src/test/java/kr/binarybard/hireo/web/member/controller/MainControllerTest.java
Labels: 🆕 enhancement, 👀 review, 🔄 API

#14 HIR-26 feat: 모든 요청에 대해 JWT 토큰의 유효성을 검증하는 필터를 구현함
  src/main/java/kr/binarybard/hireo/config/SecurityConfig.java
  src/main/java/kr/binarybard/hireo/config/jwt/JwtAccessDeniedHandler.java
  src/main/java/kr/binarybard/hireo/config/jwt/JwtAuthTokenFilter.java
  src/main/java/kr/binarybard/hireo/config/jwt/JwtAuthenticationEntryPoint.java
  src/test/java/kr/binarybard/hireo/api/auth/controller/AuthenticationApiControllerTest.java
Labels: 🆕 enhancement, 👀 review, 🔒 security

#15 HIR-27 feat: JWT 토큰 유효성 검증에 실패할 경우 적절한 에러 메시지를 반환하는 로직을 구현함
  build.gradle
  src/main/java/kr/binarybard/hireo/api/auth/controller/AuthenticationApiController.java
  src/main/java/kr/binarybard/hireo/api/auth/service/RefreshTokenService.java
  src/main/java/kr/binarybard/hireo/api/common/advice/GlobalExceptionHandler.java
  src/main/java/kr/binarybard/hireo/api/common/dto/ErrorResponse.java
  src/main/java/kr/binarybard/hireo/api/common/exceptions/AuthException.java
  src/main/java/kr/binarybard/hireo/api/common/exceptions/BusinessException.java
  src/main/java/kr/binarybard/hireo/api/common/exceptions/EntityNotFoundException.java
  src/main/java/kr/binarybard/hireo/api/common/exceptions/ErrorCode.java
  src/main/java/kr/binarybard/hireo/api/common/exceptions/InvalidValueException.java
  src/test/java/kr/binarybard/hireo/api/auth/controller/AuthenticationApiControllerTest.java
Labels: 👀 review, 🔄 API, 🔒 security

#17 HIR-29 feat: 웹에서도 각 예외 유형별에 따라 적절한 에러 페이지로 리다이렉트 시킴
  src/main/java/kr/binarybard/hireo/api/auth/controller/AuthenticationApiController.java
  src/main/java/kr/binarybard/hireo/api/auth/service/RefreshTokenService.java
  src/main/java/kr/binarybard/hireo/api/common/exceptions/AuthException.java
  src/main/java/kr/binarybard/hireo/api/common/exceptions/BusinessException.java
  src/main/java/kr/binarybard/hireo/api/common/exceptions/EntityNotFoundException.java
  src/main/java/kr/binarybard/hireo/api/common/exceptions/InvalidValueException.java
  src/main/java/kr/binarybard/hireo/common/advice/RestApiExceptionHandler.java
  src/main/java/kr/binarybard/hireo/common/advice/WebExceptionHandler.java
  src/main/java/kr/binarybard/hireo/common/dto/ErrorResponse.java
  src/main/java/kr/binarybard/hireo/common/exceptions/AuthException.java
  src/main/java/kr/binarybard/hireo/common/exceptions/BusinessException.java
  src/main/java/kr/binarybard/hireo/common/exceptions/EntityNotFoundException.java
  src/main/java/kr/binarybard/hireo/common/exceptions/ErrorCode.java
  src/main/java/kr/binarybard/hireo/common/exceptions/InvalidValueException.java
  src/main/java/kr/binarybard/hireo/config/oauth/userinfo/CustomOAuth2UserInfo.java
  src/main/java/kr/binarybard/hireo/exception/CompanyNotFoundException.java
  src/main/java/kr/binarybard/hireo/exception/DuplicateEmailException.java
  src/main/java/kr/binarybard/hireo/exception/MemberNotFoundException.java
  src/main/java/kr/binarybard/hireo/exception/UnsupportedOAuth2ProviderException.java
  src/main/java/kr/binarybard/hireo/web/auth/controller/LoginController.java
  src/main/java/kr/binarybard/hireo/web/auth/service/LoginService.java
  src/main/java/kr/binarybard/hireo/web/company/controller/CompanyController.java
  src/main/java/kr/binarybard/hireo/web/company/service/CompanyService.java
  src/main/java/kr/binarybard/hireo/web/member/service/MemberService.java
  src/main/resources/messages.properties
  src/main/resources/templates/error/401.html
  src/main/resources/templates/error/403.html
  src/main/resources/templates/error/default.html
  src/test/java/kr/binarybard/hireo/web/auth/controller/LoginControllerTest.java
  src/test/java/kr/binarybard/hireo/web/company/controller/CompanyControllerTest.java
  src/test/java/kr/binarybard/hireo/web/company/service/CompanyServiceTest.java
  src/test/java/kr/binarybard/hireo/web/member/service/MemberServiceTest.java
Labels: 🆕 enhancement, 👀 review

#18 Hir 12 company register
  src/main/java/kr/binarybard/hireo/common/CurrentUser.java
  src/main/java/kr/binarybard/hireo/common/exceptions/ErrorCode.java
  src/main/java/kr/binarybard/hireo/web/company/controller/CompanyController.java
  src/main/java/kr/binarybard/hireo/web/company/domain/Company.java
  src/main/java/kr/binarybard/hireo/web/company/domain/Industry.java
  src/main/java/kr/binarybard/hireo/web/company/dto/CompanyMapper.java
  src/main/java/kr/binarybard/hireo/web/company/dto/CompanyRegister.java
  src/main/java/kr/binarybard/hireo/web/company/dto/CompanyResponse.java
  src/main/java/kr/binarybard/hireo/web/company/service/CompanyService.java
  src/main/java/kr/binarybard/hireo/web/location/domain/Address.java
  src/main/java/kr/binarybard/hireo/web/location/dto/LocationDto.java
  src/main/java/kr/binarybard/hireo/web/location/service/LocationService.java
  src/main/java/kr/binarybard/hireo/web/member/domain/Member.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/messages.properties
  src/main/resources/templates/company/company-form.html
  src/main/resources/templates/templates/layouts/home.html
  src/test/java/kr/binarybard/hireo/web/company/controller/CompanyControllerTest.java
  src/test/java/kr/binarybard/hireo/web/company/service/CompanyServiceTest.java
  src/test/java/kr/binarybard/hireo/web/fixture/MemberFixture.java
  src/test/java/kr/binarybard/hireo/web/location/service/LocationServiceTest.java
Labels: 🆕 enhancement, 👀 review

#19 HIR-19 feat: 사용자는 회사 프로필을 즐겨찾기에 추가하거나 제거할 수 있음
  build.gradle
  src/main/java/kr/binarybard/hireo/api/auth/service/RefreshTokenService.java
  src/main/java/kr/binarybard/hireo/api/bookmark/controller/BookmarkApiController.java
  src/main/java/kr/binarybard/hireo/api/bookmark/domain/Bookmark.java
  src/main/java/kr/binarybard/hireo/api/bookmark/dto/BookmarkMapper.java
  src/main/java/kr/binarybard/hireo/api/bookmark/dto/BookmarkResponse.java
  src/main/java/kr/binarybard/hireo/api/bookmark/repository/BookmarkRepository.java
  src/main/java/kr/binarybard/hireo/api/bookmark/service/BookmarkService.java
  src/main/java/kr/binarybard/hireo/common/BaseMapper.java
  src/main/java/kr/binarybard/hireo/common/exceptions/ErrorCode.java
  src/main/java/kr/binarybard/hireo/config/CommonConfig.java
  src/main/java/kr/binarybard/hireo/web/company/controller/CompanyController.java
  src/main/java/kr/binarybard/hireo/web/company/dto/CompanyResponse.java
  src/main/java/kr/binarybard/hireo/web/company/repository/CompanyRepository.java
  src/main/java/kr/binarybard/hireo/web/member/domain/Member.java
  src/main/java/kr/binarybard/hireo/web/member/dto/MemberMapper.java
  src/main/java/kr/binarybard/hireo/web/member/dto/MemberResponse.java
  src/main/java/kr/binarybard/hireo/web/member/repository/MemberRepository.java
  src/main/java/kr/binarybard/hireo/web/member/service/MemberService.java
  src/main/resources/data.sql
  src/main/resources/static/js/custom.js
  src/main/resources/templates/company/profile.html
  src/test/java/kr/binarybard/hireo/api/auth/service/RefreshTokenServiceTest.java
  src/test/java/kr/binarybard/hireo/api/bookmark/controller/BookmarkApiControllerTest.java
  src/test/java/kr/binarybard/hireo/api/bookmark/service/BookmarkServiceTest.java
  src/test/java/kr/binarybard/hireo/utils/ConvertUtilsTest.java
  src/test/java/kr/binarybard/hireo/web/company/controller/CompanyControllerTest.java
  src/test/java/kr/binarybard/hireo/web/company/service/CompanyServiceTest.java
  src/test/java/kr/binarybard/hireo/web/fixture/BookmarkFixture.java
  src/test/java/kr/binarybard/hireo/web/fixture/MemberFixture.java
  src/test/java/kr/binarybard/hireo/web/member/service/MemberServiceTest.java
Labels: 🆕 enhancement, 👀 review, 🔄 API

#20 HIR-31 refactor: 테스트 구조 개선
  src/test/java/kr/binarybard/hireo/api/auth/controller/AuthenticationApiControllerTest.java
  src/test/java/kr/binarybard/hireo/api/bookmark/controller/BookmarkApiControllerTest.java
  src/test/java/kr/binarybard/hireo/api/bookmark/service/BookmarkServiceTest.java
  src/test/java/kr/binarybard/hireo/common/AcceptanceTest.java
  src/test/java/kr/binarybard/hireo/common/fixture/BookmarkFixture.java
  src/test/java/kr/binarybard/hireo/common/fixture/CompanyFixture.java
  src/test/java/kr/binarybard/hireo/common/fixture/LocationFixture.java
  src/test/java/kr/binarybard/hireo/common/fixture/LoginFixture.java
  src/test/java/kr/binarybard/hireo/common/fixture/MemberFixture.java
  src/test/java/kr/binarybard/hireo/web/auth/controller/LoginControllerTest.java
  src/test/java/kr/binarybard/hireo/web/company/controller/CompanyControllerTest.java
  src/test/java/kr/binarybard/hireo/web/company/service/CompanyServiceTest.java
  src/test/java/kr/binarybard/hireo/web/location/service/LocationServiceTest.java
  src/test/java/kr/binarybard/hireo/web/member/controller/MainControllerTest.java
  src/test/java/kr/binarybard/hireo/web/member/service/MemberServiceTest.java
Labels: 🆕 enhancement, 👀 review

#21 HIR-32 feat: 서버에 파일을 업로드 하는 기능 추가
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/kr/binarybard/hireo/api/file/controller/FileApiController.java
  src/main/java/kr/binarybard/hireo/api/file/dto/FileResponse.java
  src/main/java/kr/binarybard/hireo/api/file/service/FileService.java
  src/main/java/kr/binarybard/hireo/common/exceptions/ErrorCode.java
  src/main/java/kr/binarybard/hireo/common/exceptions/FileProcessingException.java
  src/main/java/kr/binarybard/hireo/config/SecurityConfig.java
  src/main/resources/application.yml
  src/test/java/kr/binarybard/hireo/api/docs/AuthenticationApiControllerTest.java
  src/test/java/kr/binarybard/hireo/api/docs/FileApiControllerTest.java
  src/test/java/kr/binarybard/hireo/api/docs/RestDocsConfiguration.java
  src/test/java/kr/binarybard/hireo/api/file/controller/FileApiControllerTest.java
  src/test/java/kr/binarybard/hireo/api/file/service/FileServiceTest.java
Labels: 📚 documentation, 🆕 enhancement, 👀 review, 🔄 API

#22 HIR-32 feat: 파일 처리 및 업로드 과정 개선
  src/main/java/kr/binarybard/hireo/api/file/controller/FileApiController.java
  src/main/java/kr/binarybard/hireo/api/file/service/FileService.java
  src/main/resources/static/api/docs/index.html
  src/test/java/kr/binarybard/hireo/api/file/service/FileServiceTest.java
Labels: 🐛 bug, 👀 review, 🔄 API

#23 build: 자바를 위한 CodeQL 분석 도구 설정 추가
  .github/workflows/codeql.yml
Labels: 👀 review, 🔒 security

#24 build: dependabot 설정 추가
  .github/dependabot.yml
Labels: 👀 review, 🔒 security

#27 HIR-12 feat: 회사 로고 등록 기능 및 오류 수정
  src/main/java/kr/binarybard/hireo/api/auth/dto/SignInRequest.java
  src/main/java/kr/binarybard/hireo/web/company/controller/CompanyController.java
  src/main/java/kr/binarybard/hireo/web/company/domain/Company.java
  src/main/java/kr/binarybard/hireo/web/company/dto/CompanyMapper.java
  src/main/java/kr/binarybard/hireo/web/company/dto/CompanyRegister.java
  src/main/java/kr/binarybard/hireo/web/company/dto/CompanyResponse.java
  src/main/java/kr/binarybard/hireo/web/company/service/CompanyService.java
  src/main/java/kr/binarybard/hireo/web/member/domain/Member.java
  src/main/resources/static/company-form.html
  src/main/resources/templates/company/company-form.html
  src/test/java/kr/binarybard/hireo/api/bookmark/controller/BookmarkApiControllerTest.java
  src/test/java/kr/binarybard/hireo/api/docs/FileApiControllerTest.java
  src/test/java/kr/binarybard/hireo/api/file/controller/FileApiControllerTest.java
  src/test/java/kr/binarybard/hireo/common/fixture/CompanyFixture.java
  src/test/java/kr/binarybard/hireo/common/fixture/FileResponseFixture.java
  src/test/java/kr/binarybard/hireo/web/company/controller/CompanyControllerTest.java
  src/test/java/kr/binarybard/hireo/web/company/service/CompanyServiceTest.java
  src/test/java/kr/binarybard/hireo/web/fixture/BookmarkFixture.java
  src/test/java/kr/binarybard/hireo/web/fixture/CompanyFixture.java
  src/test/java/kr/binarybard/hireo/web/fixture/CompanyRegisterFixture.java
  src/test/java/kr/binarybard/hireo/web/fixture/CompanyResponseFixture.java
  src/test/java/kr/binarybard/hireo/web/fixture/LocationDtoFixture.java
  src/test/java/kr/binarybard/hireo/web/fixture/LocationFixture.java
  src/test/java/kr/binarybard/hireo/web/fixture/LoginFixture.java
  src/test/java/kr/binarybard/hireo/web/fixture/MemberFixture.java
  src/test/java/kr/binarybard/hireo/web/location/service/LocationServiceTest.java
Labels: 🆕 enhancement, 👀 review

#28 HIR-4 refactor: 로그인 API의 컨트롤러에 있던 비즈니스 로직을 서비스 계층으로 이동함
  src/main/java/kr/binarybard/hireo/api/auth/controller/AuthenticationApiController.java
  src/main/java/kr/binarybard/hireo/api/auth/dto/TokenResponse.java
  src/main/java/kr/binarybard/hireo/api/auth/service/JwtLoginService.java
  src/main/java/kr/binarybard/hireo/api/auth/service/JwtTokenService.java
  src/main/java/kr/binarybard/hireo/api/auth/service/RefreshTokenService.java
  src/test/java/kr/binarybard/hireo/api/auth/controller/AuthenticationApiControllerTest.java
  src/test/java/kr/binarybard/hireo/api/auth/service/JwtLoginServiceTest.java
  src/test/java/kr/binarybard/hireo/api/auth/service/JwtTokenServiceTest.java
  src/test/java/kr/binarybard/hireo/api/docs/AuthenticationApiControllerTest.java
  src/test/java/kr/binarybard/hireo/common/fixture/MemberFixture.java
Labels: 👀 review, 🔄 API
